### ISSUE TITLE
Consistently refer to pre/post-conditions in docstrings

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#216]
This is a _very_ minor issue, but we are currently very inconsistent with our usage of pre-condition vs pre condition. However, precondition (without a space or hyphen) is an accepted word, as is postcondition, so we should replace these consistently in the docs.

**Comment by bdice** [comment]
The docstrings side of this issue is fixed by the combination of #387, #389, and #392. However, internal names like `_collect_pre_conditions` and `_OPERATION_PRE_CONDITIONS` still exist. Those should be replaced with names like `_collect_preconditions` and `_OPERATION_PRECONDITIONS`. I think these changes would be confined to `flow/project.py` and `tests/test_project.py`.
