### ISSUE TITLE
Inconsistent eligibility check for _main_script

### ISSUE THREAD

**Issue by zhou-pj** [glotzerlab/signac-flow#218]
### Description

As pointed out by @vyasr, there is inconsistent eligibility check in def _main_script() depending on whether cmd option is provided or not. Is there specific reason for this or should we make them consistent?

**Comment by vyasr** [comment]
To give a little more information here:

Currently `FlowProject._main_script` generates operations in this block of code:

```python
with self._potentially_buffered():
    if args.cmd:
        operations = self._generate_operations(args.cmd, jobs, args.requires)
    else:
        operations = self._get_pending_operations(jobs, args.operation_name)
    operations = list(islice(operations, args.num))
```

The issue is that `_generate_operations` will not check eligibility of operations before generating operation, whereas `_get_pending_operations` will check this. Before we can change anything, we need to establish what the correct behavior is. The two reasonable options in my opinion are:

1. `script` should always output, even if the operation is ineligible.
2. `script` should only output in the cases where `submit --pretend` would output.

**Comment by csadorf** [comment]
@vyasr I vote for 2. Whether we can make this behavior standard depends on whether we classify the current behavior as a bug.

**Comment by vyasr** [comment]
I also think option two makes sense. I would definitely classify this behavior as a bug, in the sense that whether or not an operation is a cmd or not should not affect condition evaluation.

**Comment by vishav1771** [comment]
@vyasr I would like to work on this issue.
