### ISSUE TITLE
allow forming unions of groups

### ISSUE THREAD

**Issue by atravitz** [glotzerlab/signac-flow#219]
### Feature description

It would be helpful to be able to create unions of groups 

### Proposed solution
``` python
simulation = Project.make_group(name="simulation")                                                      
analysis = Project.make_group(name="analysis")   
all = Project.make_group.union(simulation, analysis)
```

**Comment by csadorf** [comment]
Generally in favor of the idea, I think a better API would be based on operator overloading:
```python
simulation_and_analysis = simulation + analysis
```
Note: I avoided the name `all`, since there is a special *all* group that actually contains all operations.

**Comment by tcmoore3** [comment]
Would it be beneficial to treat the groups as `set`s, and then implement all of the set operations for groups (or at least the ones that make sense; I can't imagine how `isdisjoint()` or `issuperset()` would be beneficial for groups)?

**Comment by b-butler** [comment]
@tcmoore3 `isdisjoint()` actually is important for submitting jobs. If the groups aren't disjoint, then we need to check if one is already submitted.

In general, I am in favor of viewing `FlowGroup`s as sets (I already mentally think of them this way), and implementing all the set operators on them with magic methods thrown in.

This however, should be done after the main groups PR #114

**Comment by bdice** [comment]
Looking at the feasibility of this -- if these could be treated like sets, then it would be as simple as inheriting from `collections.abc.MutableSet` and implementing the following:
- [x] `__contains__`
- [x] `__iter__`
- [ ] `__len__`
- [ ] `add`
- [ ] `discard`
All the other operations (`__le__`, `__lt__`, `__eq__`, `__ne__`, `__gt__`, `__ge__`, `__and__`, `__or__`, `__sub__`, `__xor__`, `isdisjoint`, `clear`, `pop`, `remove`, `__ior__`, `__iand__`, `__ixor__`, and `__isub__`) come for free if you implement that interface.

However, it's not clear to me if this is really set-like. It seems more like a mapping of "name" to "operation" from a brief look at the source.

**Comment by b-butler** [comment]
@bdice Hmm, it isn't internally represented that way. In a sense a `FlowGroup` is a subset of all available operations with a few caveats. We could add all those methods though from my understanding. There would be a complication with directives, though.

**Comment by b-butler** [comment]
When I said viewing them as sets, I meant that those operations should be available to `FlowGroup`s not that they are just sets or that they are internally represented that way.

**Comment by vyasr** [comment]
When I first saw Tim's proposal I also thought about `MutableSet`, but I had the same reservations about why this could get dicey. What we roughly want is something that implements both `MutableSet` and `MutableMapping`, where `add` and `discard` would have to take `(key, value)` tuples in order to insert them. At a high level, I actually think multiple inheritance of this form could work; we would have to be very careful to make sure that things like comparison operators are inheriting the right version in all cases though.

**Comment by vyasr** [comment]
@atravitz did you have any further thoughts on how this should behave?

@bdice @csadorf @zhou-pj you were all involved in the discussion we had here, and I believe our conclusion was that we should come back to this discussion after groups were merged. IIRC none of us were clear on exactly what use-case we wanted to support, with the primary issue being that we needed to resolve questions about how directives would be merged. Is that correct? If so, should we open a separate issue to discuss how to handle merging (or not merging) directives between groups and operations?

**Comment by bdice** [comment]
We could skip implementing this feature for now, and tell users to create bigger groups by repeating the operations and directives from smaller groups if they need this. The complexity of the directives-merging strategy makes me hesitant from a cost/benefit perspective:
- somewhat hard to document and test effectively, since there are tons of edge cases and no intuitive strategy for resolution
- use cases are somewhat ambiguous
- probably only serves a very niche set of users
- alternatives exist like manually creating a bigger group

Just trying to keep the feature creep to a minimum.

**Comment by vyasr** [comment]
IIRC Alyssa's original goal was to have this work by just merging operations and not do any directive merging, but we determined that this really wasn't very useful because you'd still have to add in directives. I'm open to skipping this in favor of limiting complexity, but I'd like to have some discussion about it before making a decision in case there is some useful low-hanging fruit or some high-impact use case we're missing.

**Comment by vyasr** [comment]
@glotzerlab/signac-committers any objections to closing this issue? I don't think we ever found clear motivation for it or defined exactly how it would be best to behave in the context of merging directives and anything else attached to a group other than its operations.

**Comment by csadorf** [comment]
@atravitz Do you still see a clear use case for this or has your opinion evolved on this feature request?

**Comment by atravitz** [comment]
I think it's fine to close this
