### ISSUE TITLE
Cluster-customizable separators in job names

### ISSUE THREAD

**Issue by rsdefever** [glotzerlab/signac-flow#224]
### Feature description

The job name separator is currently '/'. When installing signac-flow on the Notre Dame CRC cluster I found that the UGE scheduler does not allow for '/' characters in the job name. @vyasr helped me create a temporary patch for our cluster by replacing the '/' characters with '-' characters.

Line 318 of project.py:

```python
        readable_name = '{}/{}/{}/{:04d}/'.format(
            str(project)[:12], str(self.job)[:8], self.name[:12], index)[:max_len]
```

EDIT: I discovered that this problem also appears with job bundling -- once again the bundled job names have the '-' separator. 

### Proposed solution

Some method that allows the separator to be cluster-specific.

**Comment by ac-optimus** [comment]
hi @rsdefever @csadorf, I would like to work on this issue. Can you please let me know how to find the list of schedulers which does not support  '/'  in their job naming?

**Comment by bdice** [comment]
@ac-optimus I don't think we have a list -- we only have one known example of such a scheduler (the UGE scheduler mentioned above). We could add a configuration variable for this separator, which would default to `"/"`, but I don't know if that's better than a custom environment or other alternative. I don't have a clear "best" solution in mind.

**Comment by vyasr** [comment]
The solution that I had in mind is to modify the `get_id` function of `JobOperation` to accept a separator argument. You would then need to have environments encode this separator, probably as a class member. Finally, you would modify all calls to `get_id` to pass the separator through so that the name is generated appropriately.

**Comment by ac-optimus** [comment]
@vyasr  surely will look into the solution. One last doubt -- Should the separator argument default to '/' as suggested by @bdice ?

**Comment by bdice** [comment]
@vyasr I think we can do slightly better - the FlowProject knows its environment in `self._environment`, and the JobOperation knows its FlowProject. I don't think that we should pass in an environment to the `get_id` function because it would be difficult to refactor and that method is used for all kinds of things internally (equality testing, hashing the JobOperation, etc.) and should be parameter-free (there is an index argument but I am ignoring that). Below, I have a suggested alternative that I mentioned in Slack.

If you look at the `get_id` function, you will see the variable project defined.
https://github.com/glotzerlab/signac-flow/blob/e46db0e8c487efdeff2789b17da0b472ce7cef12/flow/project.py#L300-L302

I think you could use `project._environment` to get the environment class.
https://github.com/glotzerlab/signac-flow/blob/e46db0e8c487efdeff2789b17da0b472ce7cef12/flow/project.py#L641-L645

Replace the `readable_name` code:
https://github.com/glotzerlab/signac-flow/blob/e46db0e8c487efdeff2789b17da0b472ce7cef12/flow/project.py#L320-L321
with:
Then define a separator and get the readable name.
```python
separator = getattr(project._environment, 'JOB_ID_SEPARATOR', '/')
readable_name = separator.join(str(project)[:12], str(self.job)[:8], self.name[:12], index)
readable_name += separator
readable_name = readable_name[:max_len]
```

Then environments can define a separator in the `JOB_ID_SEPARATOR` attribute. Users with this issue would be able to define a custom environment class for their cluster with that attribute set to something else besides `/`.

**Comment by vyasr** [comment]
I wasn't suggesting passing the environment as an argument, just the separator. Accessing `project._environment` inside `get_id` isn't enough, because the user could pass a different environment in and we need to respect that (see e.g. the `env` argument to `submit`). I realize that the `get_id` function gets called in a lot of places, and a lot of function signatures may have to be modified to allow passing the environment through, so I'm open to alternative ways of addressing this. Unfortunately, allowing users to pass different environments to flow makes this quite a bit more complicated than it would be otherwise.

**Comment by ac-optimus** [comment]
I think a small addition to @bdice proposed solution would work. Since we pass `env` to `submit` method we can extract the separator in the similar way as in the above solution but before calling `get_id`. We extract separator argument first maybe in `_store_bundled` method or in `submit_operation` and then pass to `_store_bundled` before calling `get_id(separator)` method. 
And in that case get_id will be modified with a small check at the initial stage --
```python
def get_id(self, saperator=None, info=0):
	if saperator:
		sep=saperator
	else:
		sep=getattr(project._environment, 'JOB_ID_SEPARATOR', '/')
        ...
        ...
```
```JOB_ID_SEPARATOR``` in `env` tempelate will have the saperator and if not then we user default '/' saperator.
For the rest `get_id` calls else condition would take care.

**Comment by vyasr** [comment]
Addressing this request without adding too much complexity will have to wait for #245. Currently the number of ways that environments can be specified makes it difficult to apply this change without changing the code in a wide range of places. Once we complete #245 we will be able to rely on `project._environment`, making this PR much simpler. I don't think we need to wait on the full deprecation cycle to take place before enabling this feature unless there's strong opposition to that.

**Comment by vyasr** [comment]
@ac-optimus it should be possible to address this issue now. You can ignore the environments passed as arguments to submit/run (since that feature is now deprecated) and just rely on `job._project.environment` to get the separator now. That way you won't have to modify get_id at all.

**Comment by ac-optimus** [comment]
> @ac-optimus it should be possible to address this issue now. You can ignore the environments passed as arguments to submit/run (since that feature is now deprecated) and just rely on `job._project.environment` to get the separator now. That way you won't have to modify get_id's signature at all.

@vyasr, will surely look into this in a day or two!

**Comment by ac-optimus** [comment]
> @ac-optimus it should be possible to address this issue now. You can ignore the environments passed as arguments to submit/run (since that feature is now deprecated) and just rely on `job._project.environment` to get the separator now. That way you won't have to modify get_id's signature at all.

@vyasr I have created a PR can you please review if this is what was required? Also, I am not sure how to go about testing it?
