### ISSUE TITLE
Simplify environment overrides

### ISSUE THREAD

**Issue by vyasr** [glotzerlab/signac-flow#245]
Currently users can override the detected environment in multiple places. In the context of a `FlowProject`, here are the possible ways that the environment to be used is determined in descending order of precedence:

1. Providing the `env` argument to `submit` and `submit_operations`.
2. Setting the environment on construction of a `FlowProject`.
3. Setting the `ENVIRONMENT` global variable in the `flow.environment` module.
4. Using the `SIGNAC_FLOW_ENVIRONMENT` environment variable.
5. Using hostname-based detection of the environment.

In the vast majority of cases, users simply fall through to (5). The ability to override environments is useful, and it is necessary for testing, so we should not remove the feature entirely. However, the presence of this many entry points is confusing, and it complicates the implementation of other features (see #224). We should reduce the number of ways that the default environment detection can be overridden.

In my opinion, option (1) should definitely be deprecated, because there is nothing that can be accomplished with that that cannot be accomplished using (2). For this reason, (2) should be maintained. (3) and (4) are somewhat redundant, but I can see reasons for potentially keeping both. We should come to a consensus on how to handle these, and then implement the resulting deprecations.

**Comment by bdice** [comment]
@vyasr I agree that (1) should be deprecated and (2) should be maintained. I also think (3) should be deprecated/removed since it's untested and does not seem useful to me (it seems like a holdover from when `flow.environments` was not automatically imported with `flow`). I think (4) and (5) are fine to keep. I would retain the current order of precedence: 2, 4, 5.

@CryoZEUS This is the issue that I was mentioning earlier. We'll need to reach some decisions and create a specific list of action items before this issue is ready for a pull request. Until we have a plan for this issue, you might read the signac-flow code and familiarize yourself with each of the environment detection methods.

**Comment by CryoZEUS** [comment]
@bdice  This looks like an interesting issue. I'd be happy to work on it and would be glad if you could assign it to me. I'll look out (or discuss if required) for the list of action items as soon as it is ready. 

That being said, I'll go through the signac-flow code in the meantime to adequately equip myself to work on the implementation of the same. Again, thank you for this opportunity.

**Comment by CryoZEUS** [comment]
I'll also go through the conversation on the flow-dev slack channel regarding this. You can PM / mention me there as well.

**Comment by csadorf** [comment]
I propose the following action items based on the issue description and @bdice 's comment:

1. [ ] Deprecate option 1.
2. [ ] Remove option 3 (without deprecation period)
3. [ ] Otherwise retain current order of precedence.

@vyasr @bdice Please mark this comment with :+1: if you agree.
@CryoZEUS Please feel free to start working on this once @vyasr and @bdice have agreed.

**Comment by CryoZEUS** [comment]
Understood, @bdice Will do.

**Comment by bdice** [comment]
@CryoZEUS This should be ready for you to start, I think we agree on what should be done. Let us know if you have questions!

**Comment by CryoZEUS** [comment]
@bdice Thanks for the go-ahead! I've got college tests this week; but I'll do my best to finish with this Issue asap. Also, I did have some doubts and I'll be posting them on slack within the next couple of days. Thanks again for the support!
