### ISSUE TITLE
Potential conditional use of Pool v. ThreadPool in status Parallization

### ISSUE THREAD

**Issue by b-butler** [glotzerlab/signac-flow#264]
### Feature description
We currently use `ThreadPool` when querying statuses i.e. `FlowProject._fetch_status`. Conditionality, allowing for process pooling instead if a label(s) is more computationally heavy than IO heavy would likely improve performance.

### Proposed solution
Currently the code that uses the `ThreadPool` could be essentially reused to work with `Pool` or `ThreadPool` given a function argument or command-line flag.

### Additional context

This idea came from a conversation I had with @justinGilmer about slow status output.

Edit: Add the function where threading currently occurs.

**Comment by vyasr** [comment]
I believe we originally chose a ThreadPool because most conditions were IO bound and because forking on login nodes was problematic on some clusters. Not sure if the latter is still the case (I believe we've tested this for other changes in flow and found that forking is fine), so in cases where the former is not true it could certainly be beneficial. Making it an option would also allow the user to choose in case forking doesn't work.

**Comment by kidrahahjo** [comment]
@vyasr can you please assign me this issue.
I had a talk with @b-butler and he thinks that this is an issue I can handle.
