### ISSUE TITLE
Jupyter operation creation and submission

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#27]
**[Original report](https://bitbucket.org/glotzer/signac-flow/issue/27) by Bradley Dice (Bitbucket: [bdice](https://bitbucket.org/bdice), GitHub: [bdice](https://github.com/bdice)).**

----------------------------------------

@daich reported: I wish I could directly use Jupyter Notebook and upgrade a notebook into a job operation. Maybe submit jobs inside the notebook?

**Comment by vyasr** [comment]
This issue is a little vague at the moment. How would you upgrade a notebook into a job operation? Do we essentially want to do something like a `%%writefile` to an existing project file? Submission inside the notebook is possible for existing operations, but for new operations they need to be added to the operation list somehow.

**Comment by csadorf** [comment]
@cheng Could you help us understand this issue better?

**Comment by jdaaph** [comment]
I think at the time I added this issue was meaning something like a python API for job submission to use a notebook cell as operation but now that I think of it it doesn't make much sense. I suggest just let the issue fly.

**Comment by vyasr** [comment]
Sounds good.
