### ISSUE TITLE
Job Name error non-obvious

### ISSUE THREAD

**Issue by rskye144** [glotzerlab/signac-flow#355]
### Description
When submitting to a compute cluster, the job-name is automatically set to {{ id }} and this is used to keep track of what is running and generate the output of "status." However, it is not obvious from the documentation that this is the behavior, so it's easy to overwrite the job name to something friendly to the user and break the tracking.

It was suggested in the help forums that I raise the issue here, so that a more obvious warning about the behavior can be put in the documentation.

### To reproduce
Use any method to manually set the job name. For example:

#SBATCH --job-name="test"

### Error output

The job doesn't register as active. The result of 
python project.py status
will always be "Unknown."

### System configuration

Please complete the following information:
(signac.__version__); import flow; print(flow.__version__)'
Linux-3.10.0-957.21.3.el7.x86_64-x86_64-with-centos-7.6.1810-Core
3.5.7 (default, Oct  7 2019, 09:32:47) 
[GCC 8.3.0]
1.2.0
0.8.0

**Comment by vyasr** [comment]
This issue was raised previously before in #164, and it was supposed to have been resolved in #241. Unfortunately, both the issue and the solving PR only addressed the case where a user overrode the job name using the command line overrides `python project.py submit ... -- --job-name="test"`. We could try to add some error detection by parsing a provided script, but I don't know how robust we can make that since scripts can extend other scripts. At minimum we can definitely add a warning to the docs.

**Comment by csadorf** [comment]
@rskye144 Thank you for creating the issue. That is very helpful. 👍 

I would suggest to:
1. Add a fat warning in the template docs that overriding the job-name will break things.
2. With respect to @vyasr suggestion, I think it is feasible to run a scheduler-specific validation function on the **final script** that can – among other things – also warn about this specific issue. I'd go as far as canceling the submission in that case and requiring the *force* option to override this.

**Comment by vyasr** [comment]
Agreed, I think the most suitable option is probably just an exact textual match, something analogous to `assert f"#PBS -N {submission_id}" in file`.

**Comment by bdice** [comment]
@shandave and I are discussing adding the warning to this file:

https://github.com/glotzerlab/signac-docs/blob/master/docs/source/templates.rst

The warning message I would suggest is:
> **signac-flow** relies on the scheduler job name to recognize the status of submitted jobs. Users should *not* set the job name manually via the command line or a custom template.

While it doesn't address the validation logic, I'm not even sure that there is a clean way to validate the final script. Nothing prohibits the user from specifying a job name option two times (e.g. in their own header and in the base script), and I suspect that proper validation would be quite difficult.

**Comment by vyasr** [comment]
> While it doesn't address the validation logic, I'm not even sure that there is a clean way to validate the final script. Nothing prohibits the user from specifying a job name option two times (e.g. in their own header and in the base script), and I suspect that proper validation would be quite difficult.

@bdice I don't follow, what do you mean by those two examples of specifying the job name? Is the header the command line argument whereas the base script is the custom script? I think validating the final script is feasible since even if the job name is overwritten multiple times only one final version will get written to the submission script, _except_ for the case where the user provides arbitrary commands to be passed to the scheduler on the command line, for which case we would  have to check the `flags` passed to `Scheduler.submit` somewhere in the call stack. Am I missing something?

**Comment by bdice** [comment]
@vyasr You're mostly right, but I'm imagining a case where the user's template has a header block that calls `super()` and then specifies another header line that defines the job name again. Something like

```python
{% extends "slurm.sh" %}
{% block header %}
{{ super () -}}
#SBATCH --job-name=MyInvalidJobName
{% endblock %}
```

What happens here? The submitted script will contain _two_ lines starting with `#SBATCH --job-name=` (the first one is correct, generated by signac-flow, and the second one is invalid). I don't know how SLURM or other schedulers would interpret the resulting script. And worse, you could have the alias `-J` so it's not enough to check for one instance of `#SBATCH --job-name=`. This just sounds like a very difficult situation to validate and I'm happy to chalk this up to user error if we document the requirement of allow signac-flow to manage job names.

**Comment by vyasr** [comment]
You're right that there are innumerable possible ways that this could go wrong. I was only suggesting to provide some help in the most obvious ways that this could fail, but it's certainly possible that what I'd consider to be the most obvious ways would not end up being the most helpful and we'd just end up playing whac-a-mole. I think adding a warning is something we can do ASAP. Beyond that, expending developer effort on this seems ill-advised since we have plenty of other things to work on.

**Comment by csadorf** [comment]
I think it should be possible to check the final rendered script just before submission, not the individual templates, no?

**Comment by bdice** [comment]
> I think it should be possible to check the final rendered script just before submission, not the individual templates, no?

@csadorf tl;dr I mentioned a few reasons in the thread why that won't work. I prefer to document that we rely on job names and then call this issue solved.

There are lots of ways that the user can break/override things. For example:

1. Using something like `python project.py submit [...] -- --job-name="potato"` on a SLURM cluster will pass an argument directly to `sbatch` that signac-flow never parses or renders into the submitted script. This is one of the real world cases that has been reported by a user as not working.
2. Aliases like `-J` for `--job-name` provide another way to alter the job name.
3. I listed [a nefarious template example above](https://github.com/glotzerlab/signac-flow/issues/355#issuecomment-775349377) where a user template could re-define the job name in a way that we can't predict how the scheduler will handle.

In each of those cases, the proposal to check the rendered script before submission won't work -- some cases could be handled if the proposed pre-submission parser is highly sophisticated, but I think that's too big of a burden on signac-flow and it is out of scope for us to prevent those kinds of user errors.

**Comment by csadorf** [comment]
> > I think it should be possible to check the final rendered script just before submission, not the individual templates, no?
> 
> @csadorf tl;dr I mentioned a few reasons in the thread why that won't work. I prefer to document that we rely on job names and then call this issue solved.

I generally follow your reasoning that it is impossible to catch all edge cases, but a very basic check for a duplicated `--job-name` or `-J` within the command line arguments or within the rendered script appears reasonable to me. But of course, it represents work and improving the documentation is much easier with higher impact.
