### ISSUE TITLE
Rename Torque to PBS (Environment, Scheduler)

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#388]
I am not sure if our scheduler classes for "Torque" are named correctly. I wonder if PBS is a more appropriate name, since our Torque scheduler works decently well with other PBS (qsub) systems that are not using Torque, in my understanding (e.g. Sun Grid Engine).

https://torqueusers.supercluster.narkive.com/zznH02ck/what-is-the-difference-between-pbs-and-torque

@csadorf @vyasr Do either of you have insight on the original choice of a name, or opinions on whether this would be good to rename? Also tagging @joaander in case he knows more about the naming/history of HPC schedulers.

**Comment by csadorf** [comment]
Yes, i think it's named incorrectly. I think at least I was just confused about the relationship at the time.

**Comment by vyasr** [comment]
I agree that PBS is a more appropriate name than Torque. We are not to my knowledge using any directives that aren't respected by any PBS implementation, but I would have to double check that. However, I'd be careful on exactly what breadth of coverage we'd want to claim. I'm not sure what you're referring to when you say that it works well with other `qsub` systems, is there a specific example (the Notre Dame or Minnesota cluster) that you're thinking of? The Sun Grid Engine scheduler is not a PBS derivative AFAIK, and while it uses (roughly) the same commands (like `qsub`) the actual submission directives are different and the headers in a script use `#$` instead of `#PBS`. So unless a system is using a very nonstandard configuration of SGE I wouldn't expect our template to be compatible, even if our environment does generate a valid submission command.

**Comment by joaander** [comment]
Yes, PBS and SGE are completely different systems and not compatible.
Every PBS-type HPC system I've used in the past ~12 years has been Torque/Moab (https://adaptivecomputing.com/) which is (or was?) a commercially supported version of torque with added features for resource scheduling. My understanding is that the main differences are on the administrative/configuration side.

OpenPBS seems to still be actively maintained (https://github.com/openpbs/openpbs). I do not know if the user commands are still compatible with Torque after so long since forking. We may only find out after users attempt to run signac-flow on an OpenPBS system. I don't think it is worth our time to build a test system and find out. We could rename Torque to PBS and later deal with any slight variations when needed.
