### ISSUE TITLE
Check for operation completion status before requesting resources?

### ISSUE THREAD

**Issue by berceanu** [glotzerlab/signac-flow#462]
Perhaps I'm missing something, but this doesn't seem to check if the `op` has its post-conditions met:

```jinja2
{% set gpu_tasks = operations|calc_tasks('ngpu', parallel, force) %}
```

https://github.com/glotzerlab/signac-flow/blob/03fe709d578980e6baba96c4862c2af18afcfc5e/flow/util/template_filters.py#L92

In case it does, it probably shouldn't be counted, right?

**Example usage**: I have 1 GPU operation and a bunch of CPU operations in [`project.py`](https://github.com/berceanu/signac-driven-fbpic/blob/b45049769e12e9b6c80b8ec32e282a59e379709a/signac/src/project.py#L196). I submit once, the GPU op completes, but some CPU ops remain. I submit the second time, but `--gres=gpu:{{ gpu_tasks }}` still counts the GPU task and asks for `--gres=gpu:1`.

Note: For submission, I do `python src/project.py submit -o ex --bundle=1 --parallel` in this example

**Comment by mikemhenry** [comment]
I'm a bit confused with what you are trying to do/ask.
The template does not encode the logic of pre/post conditions.

Did this work?
```
{% set gpus = operations|map(attribute='directives.ngpu')|sum %}

{% if gpus %}
#SBATCH --gres gpu:{{ gpus }}
{% endif %}

**Comment by vyasr** [comment]
Post condition checks happen upstream of template script generation. By the time any template filter like this is called, operations have already been filtered to only include eligible operations. Specifically, when calling `submit` it calls `_get_submission_operations` [here](https://github.com/glotzerlab/signac-flow/blob/master/flow/project.py#L3612) which is responsible for checking eligibility (see [here](https://github.com/glotzerlab/signac-flow/blob/master/flow/project.py#L3290)). The templates are not well-equipped to handle such requests because depending on bundling/parallelism settings you may be grouping the operations into multiple cluster jobs and each script needs to know  the right number of operations a priori, so the template filters are designed with that in mind.
