### ISSUE TITLE
The TORQUE scheduler is_present() method triggers subprocess.CalledProcessError

### ISSUE THREAD

**Issue by csadorf** [glotzerlab/signac-flow#53]
### Description

The TORQUE scheduler is_present() method forks to `qsub -V` to determine whether the scheduler is present. On some systems this fork will return with an exit status, because the current context does not allow for submission, e.g., on a compute node.

### To reproduce

For example, try to call `project.py status` on a Cray compute node.

**Comment by csadorf** [comment]
Fixed by pull request #54.

**Comment by bdice** [comment]
@csadorf Which system caused this issue? Is that system still in production? I ran into a problem with @klywang and we might want to revert PR #54 so that `is_present` returns `False` on systems where the scheduler version command fails (i.e. `bjobs -V` or `qsub --version` returning a non-zero exit code).

**Comment by csadorf** [comment]
> @csadorf Which system caused this issue? Is that system still in production? @klywang ran into a problem and we might want to revert PR #54. (I'll let @klywang create a separate issue to document what's going wrong.)

This was probably on either titan or summit, but I do not remember anymore, sorry.

**Comment by vyasr** [comment]
I'd assume from the combination of Torque and Cray that this was on Titan.
