### ISSUE TITLE
Tests fail when using with_job decorator on Windows

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-flow#598]
### Description
When testing signac-flow on windows, operations using the with_job decorator throws an exception.

### Error output

>input = None, capture_output = False, timeout = None, check = True
>popenargs = ('trap "cd $(pwd)" EXIT && cd C:\\Users\\hardi\\AppData\\Local\\Temp\\signac-flow_qcv7l8ws\\workspace\\017d53deb17a290d8b0d2ae02fa8bd9d && echo \'hello\' > world.txt',)
>kwargs = {'shell': True}, process = <Popen: returncode: 1 args: 'trap "cd $(pwd)" EXIT && cd C:\\Users\\hardi\\A...>
>stdout = None, stderr = None, retcode = 1

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Windows 10
 - Version of Python [e.g. 3.7]: 3.7
 - Version of signac [e.g. 1.0]: 1.7.0
 - Version of signac-flow: 0.17.0

**Comment by bdice** [comment]
![image](https://user-images.githubusercontent.com/3943761/147963725-29a6f06a-413f-4e6e-805e-216ed672e7f9.png)

**Comment by bdice** [comment]
I'm not sure if we should close this issue yet since the problem hasn't been addressed. WSL compatibility is not the same as Windows compatibility (WSL is the same as Linux for the purposes of the signac framework).

However, 53 out of 318 tests are currently failing on Windows (I just tested it locally). Given that, I am fine with closing this issue as "won't fix, at least for now" because we would need to do significant work to improve Windows compatibility overall and there is not much current interest in that from our users.
