### ISSUE TITLE
Merge requirements-dev and requirements-precommit

### ISSUE THREAD

**Issue by kidrahahjo** [glotzerlab/signac-flow#623]
### Feature description

We ask developers to set up the development environment before contributing to `signac-flow`. This involves installing several dependencies mentioned in the `requirements` directory. Since `pre-commit` is a "dev" requirement, I suggest we don't keep an extra file for the same.

### Proposed solution

Move the requirements mentioned in `requirements/requirements-precommit.txt` to `requirements/requirements-dev.txt`.

**Comment by kidrahahjo** [comment]
I am adding the "good first issue" tag here. In case this change is not required, feel free to close this issue.

**Comment by bdice** [comment]
In the past we needed these files to be separate so that our CI style checks would run as quickly as possible. We only needed to install pre-commit. https://github.com/glotzerlab/signac-flow/blob/6137f70f65fa58f982c922baa4db235b96df5e1f/.circleci/config.yml#L31

However, now that we use pre-commit.ci, we can merge these files since our CircleCI jobs don’t need to run style checks via pre-commit.

**Comment by bdice** [comment]
When addressing this issue, we should also delete the `pre-checks` job from the CircleCI configuration since it’s not used anymore.
