### ISSUE TITLE
@FlowProject.pre.after() not working as expected 

### ISSUE THREAD

**Issue by lois-181** [glotzerlab/signac-flow#789]
I ran into some non-intuitive behaviour whilst attempting to create a workflow with operations dependent on the state point of each job. Specifically, `@MyProject.pre.after(operation_2i)` (where `operation_2i` only executes on jobs with `statepoint = B`) is being ignored.

A minimal example to reproduce the issue (with two jobs, one with statepoint = A, one with statepoint = B)

```from flow import FlowProject

class MyProject(FlowProject):
    pass


def condition_A(job):
    '''peform job if statepoint = A'''
    if not job.statepoint().get("statepoint") == "A": 
        return True  
    
def condition_B(job): 
    '''perform job if statepoint = B'''
    if not job.statepoint().get("statepoint") == "B": 
        return True

@MyProject.post(condition_A)
@MyProject.operation(with_job=True)
def operation_1(job):
    with job:
        return print("operation 1" + ": " + str(job.statepoint().get("statepoint")))

@MyProject.post(condition_B)
@MyProject.operation(with_job=True)
def operation_2i(job):
    with job:
        return print("operation 2i" + ": " + str(job.statepoint().get("statepoint")))
    
@MyProject.pre.after(operation_2i)
@MyProject.operation(with_job=True)
def operation_2ii(job):
    with job:
        return print("operation 2ii" + ": " + str(job.statepoint().get("statepoint"))) 
```
and the output is:

```
operation 2i: B
operation 1: A
operation 2ii: A
```

`operation_2i` and `operation_1` correctly have only been executed on the jobs specified in their post conditions but then the expected behaviour was that `operation_2ii` would run after `operation_2i` if the post condition for `operation_2i` is also met (`condition_B`) and therefore should only run on the job with `statepoint = B`. Instead from the output we can see `operation_2ii` was not executed in the job with `statepoint = B` but was on the job with `statepoint = A`.

Please complete the following information:

 - Operating System [e.g. macOS]: Windows-10-10.0.22621-SP0
 - Version of Python [e.g. 3.7]: 3.11.4
 - Version of signac [e.g. 1.0]: 2.1.0
 - Version of signac-flow: 0.26.1

**Comment by b-butler** [comment]
@lois-181 this isn't a bug. You are using postconditions in a way not anticipated by `flow`.   In your case you use the `post` decorator as a filter stating that jobs which meet the condition are done. We recommend using preconditions to filter out jobs if that is desired. Semantically this makes sense, as filtered jobs are not finished they don't even meet the conditions to run.

However, the specific reason for the behavior in your case is `FlowProject.pre.after` takes the postconditions from the operation and use them as preconditions. This means your finished jobs (since you use `post` to filter) are the only ones eligible for `operation_2ii`.
